"""add doctors table and update medical records

Revision ID: 3e4cc0e395fe
Revises: 
Create Date: 2026-03-25 08:10:38.890789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e4cc0e395fe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.alter_column('medical_records', 'blood_type',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('medical_records', 'admitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_foreign_key(None, 'medical_records', 'doctors', ['doctor_id'], ['id'])
    op.drop_column('medical_records', 'doctor')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medical_records', sa.Column('doctor', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'medical_records', type_='foreignkey')
    op.alter_column('medical_records', 'admitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('medical_records', 'blood_type',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    op.drop_column('medical_records', 'doctor_id')
    # ### end Alembic commands ###
